# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0002_auto_20161222_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='rafflemaster',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
    ]
