# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0003_auto_20161222_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
