# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0004_raffle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rafflie.Raffle'),
        ),
    ]
