# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0009_auto_20161226_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='fine_print',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
