# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0010_auto_20161226_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='featured',
            field=models.IntegerField(default=0),
        ),
    ]
