# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0011_raffle_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafflie.Raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafflie.User')),
            ],
        ),
    ]
