# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0013_raffle_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TicketOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tickets', models.IntegerField(default=0)),
                ('full_description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='availableticket',
            name='ticket_opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafflie.TicketOpportunity'),
        ),
        migrations.AddField(
            model_name='availableticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafflie.User'),
        ),
    ]
