# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rafflie', '0014_auto_20170114_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 6, 49, 56, 239483, tzinfo=utc)),
        ),
    ]
